//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 07/07/2016 12:25:07 p.m.
namespace Servicios
{
    /// <summary>
    /// There are no comments for SDLPoC in the schema.
    /// </summary>
    public partial class SDLPoC : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new SDLPoC object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public SDLPoC(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "com.cairone.sdlpocjpa", "Servicios");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Servicios", global::System.StringComparison.Ordinal))
            {
                return string.Concat("com.cairone.sdlpocjpa.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Paises in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Pais> Paises
        {
            get
            {
                if ((this._Paises == null))
                {
                    this._Paises = base.CreateQuery<Pais>("Paises");
                }
                return this._Paises;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Pais> _Paises;
        /// <summary>
        /// There are no comments for Paises in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public void AddToPaises(Pais pais)
        {
            base.AddObject("Paises", pais);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private const string Edmx = @"<edmx:Edmx xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"" Version=""4.0"">
  <edmx:DataServices>
    <Schema xmlns=""http://docs.oasis-open.org/odata/ns/edm"" Namespace=""com.cairone.sdlpocjpa"">
      <EntityType Name=""Pais"">
        <Key>
          <PropertyRef Name=""id""></PropertyRef>
        </Key>
        <Property Name=""id"" Type=""Edm.Int32"" Nullable=""true""></Property>
        <Property Name=""descripcion"" Type=""Edm.String"" Nullable=""false""></Property>
        <Property Name=""nacionalidad"" Type=""Edm.String"" Nullable=""true""></Property>
        <Property Name=""prefijo"" Type=""Edm.Int32"" Nullable=""true""></Property>
        <Property Name=""paraisoFiscal"" Type=""Edm.Boolean"" Nullable=""true""></Property>
        <Property Name=""noColaboraLd"" Type=""Edm.Boolean"" Nullable=""true""></Property>
      </EntityType>
      <EntityContainer Name=""SDLPoC"">
        <EntitySet Name=""Paises"" EntityType=""com.cairone.sdlpocjpa.Pais""></EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for PaisSingle in the schema.
    /// </summary>
    public partial class PaisSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Pais>
    {
        /// <summary>
        /// Initialize a new PaisSingle object.
        /// </summary>
        public PaisSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new PaisSingle object.
        /// </summary>
        public PaisSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new PaisSingle object.
        /// </summary>
        public PaisSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Pais> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Pais in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("id")]
    [global::Microsoft.OData.Client.EntitySet("Paises")]
    public partial class Pais : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Pais object.
        /// </summary>
        /// <param name="descripcion">Initial value of descripcion.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public static Pais CreatePais(string descripcion)
        {
            Pais pais = new Pais();
            pais.descripcion = descripcion;
            return pais;
        }
        /// <summary>
        /// There are no comments for Property id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _id;
        partial void OnidChanging(global::System.Nullable<int> value);
        partial void OnidChanged();
        /// <summary>
        /// There are no comments for Property descripcion in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string descripcion
        {
            get
            {
                return this._descripcion;
            }
            set
            {
                this.OndescripcionChanging(value);
                this._descripcion = value;
                this.OndescripcionChanged();
                this.OnPropertyChanged("descripcion");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _descripcion;
        partial void OndescripcionChanging(string value);
        partial void OndescripcionChanged();
        /// <summary>
        /// There are no comments for Property nacionalidad in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public string nacionalidad
        {
            get
            {
                return this._nacionalidad;
            }
            set
            {
                this.OnnacionalidadChanging(value);
                this._nacionalidad = value;
                this.OnnacionalidadChanged();
                this.OnPropertyChanged("nacionalidad");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private string _nacionalidad;
        partial void OnnacionalidadChanging(string value);
        partial void OnnacionalidadChanged();
        /// <summary>
        /// There are no comments for Property prefijo in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<int> prefijo
        {
            get
            {
                return this._prefijo;
            }
            set
            {
                this.OnprefijoChanging(value);
                this._prefijo = value;
                this.OnprefijoChanged();
                this.OnPropertyChanged("prefijo");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<int> _prefijo;
        partial void OnprefijoChanging(global::System.Nullable<int> value);
        partial void OnprefijoChanged();
        /// <summary>
        /// There are no comments for Property paraisoFiscal in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<bool> paraisoFiscal
        {
            get
            {
                return this._paraisoFiscal;
            }
            set
            {
                this.OnparaisoFiscalChanging(value);
                this._paraisoFiscal = value;
                this.OnparaisoFiscalChanged();
                this.OnPropertyChanged("paraisoFiscal");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<bool> _paraisoFiscal;
        partial void OnparaisoFiscalChanging(global::System.Nullable<bool> value);
        partial void OnparaisoFiscalChanged();
        /// <summary>
        /// There are no comments for Property noColaboraLd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public global::System.Nullable<bool> noColaboraLd
        {
            get
            {
                return this._noColaboraLd;
            }
            set
            {
                this.OnnoColaboraLdChanging(value);
                this._noColaboraLd = value;
                this.OnnoColaboraLdChanged();
                this.OnPropertyChanged("noColaboraLd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        private global::System.Nullable<bool> _noColaboraLd;
        partial void OnnoColaboraLdChanging(global::System.Nullable<bool> value);
        partial void OnnoColaboraLdChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.4.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Servicios.Pais as global::Servicios.PaisSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Servicios.PaisSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Servicios.Pais> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Servicios.PaisSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Servicios.Pais as global::Servicios.PaisSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Servicios.PaisSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Servicios.Pais> source,
            global::System.Nullable<int> id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "id", id }
            };
            return new global::Servicios.PaisSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
